const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const mock=`window.mockOffline=false;window.mockCalls=[];window.mockGame=null;window.mockRow={id:'test-match',fen:'start',move_history:[],version:0,turn:'white',status:'active',white_time_ms:180000,black_time_ms:180000,initial_seconds:180,increment_seconds:2,clock_type:'total',time_control:'blitz3_2',turn_started_at:new Date().toISOString()};
window.mockRow=JSON.parse(localStorage.getItem('test-server-row')||'null')||window.mockRow;
window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'white'}}}}),updateUser:async()=>({}),signInAnonymously:async()=>({data:{user:{id:'white'}}})},rpc:async(name,args)=>{mockCalls.push({name,args});return {data:name==='heartbeat_presence'?2:name==='get_queue_counts'?[{time_control:'any',players:1}]:name==='find_match'?[{state:'matched',match_id:'test-match',color:'white',opponent_nickname:'Test'}]:[]}},functions:{invoke:async(name,{body})=>{mockCalls.push({name,body});if(mockOffline)return {error:new Error('offline')};if(body.action==='move'){if(!mockGame){mockGame=new Chess();for(const m of mockRow.move_history)mockGame.move(m)}mockGame.move(body.move);mockRow={...mockRow,fen:mockGame.fen(),move_history:mockGame.history({verbose:true}).map(m=>({from:m.from,to:m.to,promotion:m.promotion})),turn:mockGame.turn()==='w'?'white':'black',version:mockRow.version+1,turn_started_at:new Date().toISOString()}}localStorage.setItem('test-server-row',JSON.stringify(mockRow));return {data:{row:mockRow,server_now:new Date().toISOString()}}}},channel:()=>({on(){return this},subscribe(){return this}}),removeChannel:async()=>{},from:()=>({select:()=>({eq:()=>({single:async()=>({data:{}})})})})})};`;
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE_PATH?{executablePath:process.env.CHROME_EXECUTABLE_PATH}:{}),args:['--no-sandbox']});try{
for(const language of ['ru','en','es','de'])for(const [width,height] of [[320,568],[390,844],[667,375],[844,390],[1366,768],[1920,1080]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(lang=>{localStorage.setItem('chess-language-v1',lang);localStorage.setItem('chess-online-nickname','Test')},language);
 await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='audit.local')return route.abort();if(u.pathname.includes('vendor/supabase/'))return route.fulfill({body:mock,contentType:'application/javascript'});const file=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));if(!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':undefined})});
 await page.goto('http://audit.local');await page.waitForFunction(()=>typeof startGame==='function');await page.click('#enter');await page.click('#start-hotseat');await page.waitForTimeout(100);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight>innerHeight||document.documentElement.scrollWidth>innerWidth),false);
 for(const selector of ['#board','.game__actions'])assert.equal(await page.evaluate(s=>{const r=document.querySelector(s).getBoundingClientRect();return r.width>0&&r.height>0&&r.left>=0&&r.top>=0&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1},selector),true,`${language} ${width}x${height} ${selector}`);
 await page.evaluate(()=>requestPromotion(1,0,0,0));assert.equal(await page.evaluate(()=>[...document.querySelectorAll('#promotion-choices button')].every(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})),true,'promotion bounds');await page.click('#promotion-cancel');
 await page.evaluate(()=>showResult('draw','Очень длинный текст результата партии. '.repeat(12)));await page.waitForTimeout(650);await page.locator('#result-menu').click();
 assert.equal(errors.length,0,errors.join('\n'));await page.close();
}
const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>localStorage.setItem('chess-online-nickname','Test'));await page.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname!=='audit.local')return route.abort();if(u.pathname.includes('vendor/supabase/'))return route.fulfill({body:mock,contentType:'application/javascript'});const f=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));return fs.existsSync(f)?route.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html'}):route.fulfill({status:404,body:''})});await page.goto('http://audit.local');await page.waitForFunction(()=>typeof startGame==='function');await page.click('#enter');await page.click('#start-online');await page.click('#online-search-any');await page.waitForFunction(()=>gameMode==='online'&&onlineConnected);assert.equal(await page.evaluate(()=>mockCalls.some(c=>c.name==='find_match'&&c.args.p_time_control==='any')),true);
 await page.evaluate(()=>move(6,4,4,4,undefined));await page.waitForFunction(()=>chess.history().length===1&&!onlineMovePending);await page.evaluate(()=>{mockOffline=true;return refreshOnlineMatch()});assert.equal(await page.evaluate(()=>onlineConnected),false);await page.evaluate(()=>{mockOffline=false;return refreshOnlineMatch()});assert.equal(await page.evaluate(()=>onlineConnected&&chess.history().length===1),true);await page.reload();await page.waitForFunction(()=>gameMode==='online'&&onlineConnected);assert.equal(await page.evaluate(()=>chess.history().length),1);
 console.log('PASS: 24 language/viewport combinations, dialogs, all-mode search, online move/history, disconnect/recovery, reload');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
